#! /bin/bash

### BEGIN INIT INFO
# Provides:          tmux music
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: tmux music
# Description:       Start tmux session with arduino music tools
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting tmux-music..."
    sudo -u pi bash -c 'cd /home/pi/Repos/versusone/arduino-music-control/ && ./start.sh'
    ;;
  stop)
    echo "Stopping tmux-music..."
    sudo -u pi bash -c 'cd /home/pi/Repos/versusone/arduino-music-control/ && ./stop.sh'
    sleep 2
    ;;
  *)
    echo "Usage: /etc/init.d/tmux-music {start|stop}"
    exit 1
    ;;
esac

exit 0
